DROP TABLE IF EXISTS APP_BASE;

DROP TABLE IF EXISTS AUTH_BASE;

DROP TABLE IF EXISTS AUTH_MENU;

DROP TABLE IF EXISTS CODE_BASE;

DROP TABLE IF EXISTS MENU_BASE;

DROP TABLE IF EXISTS SERIAL_BASE;

DROP TABLE IF EXISTS SERIAL_MUTEX;

DROP TABLE IF EXISTS USER_AUTH;

DROP TABLE IF EXISTS USER_BASE;

DROP TABLE IF EXISTS USER_IMAGE;

DROP TABLE IF EXISTS SPRING_SESSION_ATTRIBUTES;

DROP TABLE IF EXISTS SPRING_SESSION;